-- Clips produced by EDIT jobs (trim/crop or split), kept for review until an
-- admin promotes or discards them (see VideoEditService).
CREATE TABLE IF NOT EXISTS public.video_clips (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    video_id bigint NOT NULL,
    job_id bigint,
    operation varchar(10) NOT NULL,
    segment_index integer,
    start_ms bigint NOT NULL,
    end_ms bigint,
    crop_x integer,
    crop_y integer,
    crop_w integer,
    crop_h integer,
    scale_w integer,
    scale_h integer,
    duration_seconds integer,
    width integer,
    height integer,
    storage_key varchar(500) NOT NULL,
    url varchar(1000) NOT NULL,
    size_bytes bigint NOT NULL DEFAULT 0,
    created_at timestamp(6) without time zone,
    expires_at timestamp(6) without time zone NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_video_clips_video_id ON public.video_clips (video_id);
