-- Archive state (mirrors deleted_at's pattern) and visibility (mirrors
-- collections' PUBLIC/UNLISTED/PRIVATE) for videos.
ALTER TABLE public.videos ADD COLUMN IF NOT EXISTS archived_at timestamp(6) without time zone;
ALTER TABLE public.videos ADD COLUMN IF NOT EXISTS visibility varchar(20) NOT NULL DEFAULT 'PUBLIC';

-- Prior versions of a video's file, kept when it's replaced or a trim/crop
-- edit is promoted, so nothing is ever silently lost (see VideoVersionService).
CREATE TABLE IF NOT EXISTS public.video_versions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    video_id bigint NOT NULL,
    storage_key varchar(500) NOT NULL,
    url varchar(1000) NOT NULL,
    file_size bigint,
    mime_type varchar(100),
    duration_seconds integer,
    width integer,
    height integer,
    note varchar(200),
    created_by varchar(100),
    created_at timestamp(6) without time zone
);

CREATE INDEX IF NOT EXISTS idx_video_versions_video_id ON public.video_versions (video_id);
