-- Locking a voice-over track (prevents accidental delete/replace) and markers
-- (named timestamps) for the video timeline editor.
ALTER TABLE public.video_dubs ADD COLUMN IF NOT EXISTS locked boolean NOT NULL DEFAULT false;

CREATE TABLE IF NOT EXISTS public.video_markers (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    video_id bigint NOT NULL,
    at_ms bigint NOT NULL,
    label varchar(200) NOT NULL,
    color varchar(20),
    created_by varchar(100),
    created_at timestamp(6) without time zone
);

CREATE INDEX IF NOT EXISTS idx_video_markers_video_id ON public.video_markers (video_id);
